PICMD_NO_ERROR = 0x01
PICMD_INVALID_FORMAT_ERROR = 0x02
PICMD_INVALID_PARITY_ERROR = 0x03
PICMD_COMMAND_NOT_FOUND_ERROR = 0x04
PICMD_INVALID_LENGTH_ERROR = 0x05
PICMD_COMMAND_FAIL_ERROR = 0x06

CMD_PING = b'AT\r\n'
CMD_PREFIX = b'AT*PIC='
CMD_PREFIX_LEN = len(CMD_PREFIX)
CMD_END = b'\r\n'
CMD_END_LEN = len(CMD_END)
CMD_LEN = 1
CMD_DATA_SIZE_LEN = 2
CMD_PARITY_LEN = 1
MAX_DATA_SIZE = 0xffff

CMD_RESULT_PREFIX = b'*PIC:'
CMD_RESULT_OK = b'\r\nOK\r\n'
CMD_RESULT_ERROR = b'\r\nERROR\r\n'
