PICMD_NO_ERROR = 0x01
PICMD_INVALID_FORMAT_ERROR = 0x02
PICMD_INVALID_PARITY_ERROR = 0x03
PICMD_COMMAND_NOT_FOUND_ERROR = 0x04
PICMD_INVALID_LENGTH_ERROR = 0x05
PICMD_COMMAND_FAIL_ERROR = 0x06

CMD_PREFIX = b'AT*CMD='
CMD_PREFIX_SIZE = len(CMD_PREFIX)
CMD_END = b'\r\n'
CMD_END_SIZE = len(CMD_END)
CMD_SIZE = 2
CMD_DATA_LENGTH_SIZE = 4
CMD_PARITY_SIZE = 2
MAX_DATA_LENGTH = 0xffff

CMD_RESULT_PREFIX = b'*CMD='
CMD_RESULT_OK = b'\r\nOK\r\n'
CMD_RESULT_ERROR = b'\r\nERROR\r\n'
